name: Azurite
main: me.keano.azurite.HCF
version: 1.0-SNAPSHOT
author: Keqno
description: Made for Azurite
api-version: 1.13
loadbefore:
  - ShopGUIPlus
  - EconomyShopGUI
softdepend:
  - Azurite-Core
  - LunarClient-API
  - ViaVersion
  - ProtocolSupport
  - Vault
  - HolographicDisplays
  - VortexPearls
  - PlaceholderAPI
  - CheatBreakerAPI
  - Alchemist
  - Holiday
  - AquaCore
  - Zoot
  - Zoom
  - Mizu
  - Atom
  - Basic
  - ZPermissions
  - HestiaCore
  - Phoenix
  - pxLoader