name: Titan
main: me.juanpiece.titan.HCF
version: 1.0-SNAPSHOT
author: juanpiece
description: Made for Titan
api-version: 1.13
loadbefore:
  - ShopGUIPlus
  - EconomyShopGUI
softdepend:
  - Titan-Core
  - LunarClient-API
  - ViaVersion
  - ProtocolSupport
  - Vault
  - HolographicDisplays
  - VortexPearls
  - PlaceholderAPI
  - CheatBreakerAPI
  - Alchemist
  - Holiday
  - AquaCore
  - Zoot
  - Zoom
  - Mizu
  - Atom
  - Basic
  - ZPermissions
  - HestiaCore
  - Phoenix
  - pxLoader